// Post-build service-worker generator (zero-dep, single process). Walks
// dist/, hashes every precachable asset, and writes dist/sw.js: cache-first
// precache with app-shell navigation fallback — fully offline after the
// first load (§12). Runs as the last step of `npm run build`.

import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist')
const PRECACHE_EXT = /\.(js|css|html|svg|png|webmanifest|woff2?)$/

// Must match vite's `base` (deploy workflow sets BASE_PATH=/nutri/).
const RAW_BASE = process.env.BASE_PATH ?? '/'
const BASE = RAW_BASE.endsWith('/') ? RAW_BASE : RAW_BASE + '/'

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

const entries = walk(DIST)
  .filter((f) => PRECACHE_EXT.test(f) && !f.endsWith('sw.js'))
  .map((f) => {
    const url = BASE + relative(DIST, f).split('\\').join('/')
    const revision = createHash('md5').update(readFileSync(f)).digest('hex').slice(0, 12)
    return { url, revision }
  })
  .sort((a, b) => a.url.localeCompare(b.url))

const versionHash = createHash('md5').update(JSON.stringify(entries)).digest('hex').slice(0, 10)

const sw = `// generated by scripts/build-sw.mjs — do not edit
const MANIFEST = ${JSON.stringify(entries)};
const CACHE = 'nutri-precache-${versionHash}';

const urlFor = (e) => {
  const u = new URL(e.url, self.location.origin);
  u.searchParams.set('__rev', e.revision);
  return u.href;
};
const PRECACHED = new Map(MANIFEST.map((e) => [new URL(e.url, self.location.origin).href, urlFor(e)]));
const SHELL = new URL('${BASE}index.html', self.location.origin).href;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => Promise.all(MANIFEST.map((e) => cache.add(new Request(urlFor(e), { cache: 'reload' })))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k.startsWith('nutri-precache-') && k !== CACHE).map((k) => caches.delete(k)))
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  const target = request.mode === 'navigate' ? PRECACHED.get(SHELL) : PRECACHED.get(url.href);
  if (!target) return;
  event.respondWith(
    caches.open(CACHE).then(async (cache) => (await cache.match(target)) ?? fetch(request))
  );
});
`

writeFileSync(join(DIST, 'sw.js'), sw)
console.log(`sw.js generated — ${entries.length} precached entries under base "${BASE}" (cache nutri-precache-${versionHash})`)
